swagger: "2.0"
info:
  title: REST api for simple route app
  version: ""
host: /
consumes:
  - application/json
  - application/xml
  - application/gob
produces:
  - application/json
  - application/xml
  - application/gob
paths:
  /api/datasets/:
    get:
      tags:
        - datasets_service
      summary: list datasets datasets_service
      description: получить все задачи для текущего пользователя
      operationId: datasets_service#list datasets
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/DatasetResponse'
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/datasets/{dataset_id}/:
    get:
      tags:
        - datasets_service
      summary: get dataset datasets_service
      description: получить задачу по id
      operationId: datasets_service#get dataset
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/DatasetsServiceGetDatasetOKResponseBody'
            required:
              - id
              - bloggers
              - status
              - title
              - posts_per_blogger
              - liked_per_post
              - commented_per_post
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
    put:
      tags:
        - datasets_service
      summary: update dataset datasets_service
      description: |-
        обновить информацию о задаче. Не меняет статус задачи, можно вызывать сколько угодно раз.
        			Нельзя вызвать для задачи, которая уже выполняется, для этого надо сначала остановить выполнение.
      operationId: datasets_service#update dataset
      parameters:
        - name: dataset_id
          in: path
          description: id задачи, которую хотим обновить
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
        - name: Update DatasetRequestBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/DatasetsServiceUpdateDatasetRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/DatasetsServiceUpdateDatasetOKResponseBody'
            required:
              - id
              - bloggers
              - status
              - title
              - posts_per_blogger
              - liked_per_post
              - commented_per_post
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/datasets/{dataset_id}/progress/:
    get:
      tags:
        - datasets_service
      summary: get progress datasets_service
      description: получить статус выполнения задачи по id
      operationId: datasets_service#get progress
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/DatasetsServiceGetProgressOKResponseBody'
            required:
              - bots_progresses
              - targets_notified
              - targets_failed
              - targets_waiting
              - done
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/datasets/{dataset_id}/start/:
    post:
      tags:
        - datasets_service
      summary: find similar datasets_service
      description: 'начать выполнение задачи '
      operationId: datasets_service#find similar
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/DatasetsServiceFindSimilarOKResponseBody'
            required:
              - dataset_id
              - status
              - bloggers
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/datasets/{dataset_id}/stop/:
    post:
      tags:
        - datasets_service
      summary: parse dataset datasets_service
      description: получить базу доноров для выбранных блогеров
      operationId: datasets_service#parse dataset
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/DatasetsServiceParseDatasetOKResponseBody'
            required:
              - dataset_id
              - status
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/datasets/draft/:
    post:
      tags:
        - datasets_service
      summary: create dataset draft datasets_service
      description: создать драфт задачи
      operationId: datasets_service#create dataset draft
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
            format: uuid
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
definitions:
  BloggerResponse:
    title: BloggerResponse
    type: object
    properties:
      dataset_id:
        type: string
        description: айди датасета, к которому принадлежит блоггер
        example: 9A05BD8A-CA8D-335E-C26E-14DB8FEBAB04
        format: uuid
      id:
        type: string
        example: EA2D3703-2B9D-E7C0-35B9-DB753C364369
        format: uuid
      is_initial:
        type: boolean
        description: является ли блоггер изначально в датасете или появился при парсинге
        example: false
      user_id:
        type: integer
        description: user_id в инстаграме, -1 если неизвестен
        example: 7884373643633930087
        format: int64
      username:
        type: string
        description: имя аккаунта в инстаграме
        example: Qui dicta corrupti et ut incidunt.
    example:
      dataset_id: 76150F6F-C16D-33A6-B049-F5AE2D7C6385
      id: 43632E4F-A034-6412-7CEA-7CD0E1AED81D
      is_initial: true
      user_id: 7428583732759085291
      username: Ipsum rerum quas nemo.
    required:
      - id
      - dataset_id
      - username
      - is_initial
      - user_id
  BloggerResponseBody:
    title: BloggerResponseBody
    type: object
    properties:
      dataset_id:
        type: string
        description: айди датасета, к которому принадлежит блоггер
        example: 0C589E55-99C1-3ED8-809A-1463C91242B6
        format: uuid
      id:
        type: string
        example: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
        format: uuid
      is_initial:
        type: boolean
        description: является ли блоггер изначально в датасете или появился при парсинге
        example: true
      user_id:
        type: integer
        description: user_id в инстаграме, -1 если неизвестен
        example: 7684303285314453046
        format: int64
      username:
        type: string
        description: имя аккаунта в инстаграме
        example: Ab est exercitationem suscipit sit.
    example:
      dataset_id: 0E0CB887-B526-812D-F285-DE018C555BB8
      id: AB12B85B-1864-53B4-4A92-3519B45D0D5E
      is_initial: false
      user_id: 1009684138831546335
      username: Magnam voluptatem nesciunt quaerat quasi incidunt sed.
    required:
      - id
      - dataset_id
      - username
      - is_initial
      - user_id
  BloggersProgressResponseBody:
    title: BloggersProgressResponseBody
    type: object
    properties:
      posts_count:
        type: integer
        description: количество выложенных постов
        example: 273730800156261240
        format: int64
      status:
        type: integer
        description: текущий статус бота, будут ли выкладываться посты
        example: 1910266738775935338
        format: int64
      user_name:
        type: string
        description: имя пользователя бота
        example: Aut rem ducimus aut.
    example:
      posts_count: 3414567951993234133
      status: 4276746145283443344
      user_name: Ratione quia et quidem nihil eligendi.
    required:
      - user_name
      - posts_count
      - status
  DatasetResponse:
    title: DatasetResponse
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponse'
        example:
          - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
            is_initial: false
            user_id: 7194315760384879922
            username: Alias blanditiis provident voluptatem.
          - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
            is_initial: false
            user_id: 7194315760384879922
            username: Alias blanditiis provident voluptatem.
          - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
            is_initial: false
            user_id: 7194315760384879922
            username: Alias blanditiis provident voluptatem.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 1869711229
        format: int32
      id:
        type: string
        example: E31B6C92-4A10-2D9D-2B43-B3362900308F
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 4846802
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 2128545017
        format: int32
      status:
        type: integer
        example: 4
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Quos non velit.
    example:
      bloggers:
        - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
          id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
          is_initial: false
          user_id: 7194315760384879922
          username: Alias blanditiis provident voluptatem.
        - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
          id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
          is_initial: false
          user_id: 7194315760384879922
          username: Alias blanditiis provident voluptatem.
        - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
          id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
          is_initial: false
          user_id: 7194315760384879922
          username: Alias blanditiis provident voluptatem.
        - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
          id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
          is_initial: false
          user_id: 7194315760384879922
          username: Alias blanditiis provident voluptatem.
      commented_per_post: 263980860
      id: AC2E8D12-84E7-ADAA-5045-93C4FF40145F
      liked_per_post: 2019466167
      posts_per_blogger: 743266314
      status: 1
      title: Qui ducimus.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
  DatasetsServiceFindSimilarBadRequestResponseBody:
    title: DatasetsServiceFindSimilarBadRequestResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      dataset_id:
        type: string
        description: id задачи
        example: Reprehenderit porro sed deleniti.
      status:
        type: integer
        example: 1
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      dataset_id: Voluptas voluptas voluptates suscipit aut rem provident.
      status: 3
    required:
      - dataset_id
      - status
      - bloggers
  DatasetsServiceFindSimilarNotFoundResponseBody:
    title: DatasetsServiceFindSimilarNotFoundResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      dataset_id:
        type: string
        description: id задачи
        example: Porro dolorem numquam rerum eveniet voluptas perspiciatis.
      status:
        type: integer
        example: 1
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      dataset_id: Ut placeat in et dolorem.
      status: 3
    required:
      - dataset_id
      - status
      - bloggers
  DatasetsServiceFindSimilarOKResponseBody:
    title: DatasetsServiceFindSimilarOKResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      dataset_id:
        type: string
        description: id задачи
        example: Voluptates voluptatem aut commodi dignissimos.
      status:
        type: integer
        example: 2
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      dataset_id: Nesciunt quas.
      status: 4
    required:
      - dataset_id
      - status
      - bloggers
  DatasetsServiceFindSimilarUnauthorizedResponseBody:
    title: DatasetsServiceFindSimilarUnauthorizedResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      dataset_id:
        type: string
        description: id задачи
        example: Commodi rerum rerum nihil explicabo.
      status:
        type: integer
        example: 4
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      dataset_id: Aut similique.
      status: 4
    required:
      - dataset_id
      - status
      - bloggers
  DatasetsServiceGetDatasetNotFoundResponseBody:
    title: DatasetsServiceGetDatasetNotFoundResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 1027395316
        format: int32
      id:
        type: string
        example: 6D98E750-AE3D-1948-4270-2B4874F82503
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 553556565
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 816721158
        format: int32
      status:
        type: integer
        example: 2
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Qui et quia quaerat minus.
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      commented_per_post: 1291221509
      id: CEF3CAF7-AB82-083A-2F08-9497BE6B7488
      liked_per_post: 477890404
      posts_per_blogger: 1656988288
      status: 4
      title: Et dolore.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
  DatasetsServiceGetDatasetOKResponseBody:
    title: DatasetsServiceGetDatasetOKResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 1501173537
        format: int32
      id:
        type: string
        example: 7F641448-35F7-7B05-AFB4-8DFCC48CED66
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 1127989764
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 1030367192
        format: int32
      status:
        type: integer
        example: 3
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Pariatur suscipit nam quos.
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      commented_per_post: 825913172
      id: D358BA94-28F1-C0F1-EA4E-E3BFBD8A6AE2
      liked_per_post: 2107277120
      posts_per_blogger: 997028186
      status: 2
      title: Repudiandae maxime tenetur.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
  DatasetsServiceGetDatasetUnauthorizedResponseBody:
    title: DatasetsServiceGetDatasetUnauthorizedResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 191540414
        format: int32
      id:
        type: string
        example: F25C441B-B3AA-5871-1077-53EACA084D5A
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 1621593061
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 1093723233
        format: int32
      status:
        type: integer
        example: 1
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Ut unde autem.
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      commented_per_post: 2076397394
      id: E058AD50-5D7F-E9A8-E010-D33044724992
      liked_per_post: 1518200256
      posts_per_blogger: 1946612498
      status: 5
      title: Neque voluptatum quia.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
  DatasetsServiceGetProgressNotFoundResponseBody:
    title: DatasetsServiceGetProgressNotFoundResponseBody
    type: object
    properties:
      bots_progresses:
        type: object
        description: результат работы по каждому боту, ключ- имя бота
        example:
          Magnam sunt.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
        additionalProperties:
          $ref: '#/definitions/BloggersProgressResponseBody'
      done:
        type: boolean
        description: закончена ли задача
        example: true
      targets_failed:
        type: integer
        description: количество аккаунтов, которых не получилось упомянуть, при перезапуске задачи будут использованы заново
        example: 131881568301839503
        format: int64
      targets_notified:
        type: integer
        description: количество аккаунтов, которых упомянули в постах
        example: 2541697808168446016
        format: int64
      targets_waiting:
        type: integer
        description: количество аккаунтов, которых не выбрали для постов
        example: 1366329025562598189
        format: int64
    example:
      bots_progresses:
        Nostrum quos rerum voluptatibus adipisci.:
          posts_count: 5241754460792455823
          status: 4341670138231604568
          user_name: Magni corrupti earum dolore ab.
      done: true
      targets_failed: 5265923202135355901
      targets_notified: 1266061003342115468
      targets_waiting: 6855266525843690568
    required:
      - bots_progresses
      - targets_notified
      - targets_failed
      - targets_waiting
      - done
  DatasetsServiceGetProgressOKResponseBody:
    title: DatasetsServiceGetProgressOKResponseBody
    type: object
    properties:
      bots_progresses:
        type: object
        description: результат работы по каждому боту, ключ- имя бота
        example:
          Ea hic fugit.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
          Eligendi laboriosam blanditiis ratione libero.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
          Nobis dolore sit cupiditate dolore laudantium.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
        additionalProperties:
          $ref: '#/definitions/BloggersProgressResponseBody'
      done:
        type: boolean
        description: закончена ли задача
        example: false
      targets_failed:
        type: integer
        description: количество аккаунтов, которых не получилось упомянуть, при перезапуске задачи будут использованы заново
        example: 498919194165844280
        format: int64
      targets_notified:
        type: integer
        description: количество аккаунтов, которых упомянули в постах
        example: 2626035262324994385
        format: int64
      targets_waiting:
        type: integer
        description: количество аккаунтов, которых не выбрали для постов
        example: 2971184709138637324
        format: int64
    example:
      bots_progresses:
        Dignissimos qui exercitationem ut est.:
          posts_count: 5241754460792455823
          status: 4341670138231604568
          user_name: Magni corrupti earum dolore ab.
        Perferendis rerum recusandae.:
          posts_count: 5241754460792455823
          status: 4341670138231604568
          user_name: Magni corrupti earum dolore ab.
      done: false
      targets_failed: 5645662481724943687
      targets_notified: 5240340533968572789
      targets_waiting: 4732356462312574418
    required:
      - bots_progresses
      - targets_notified
      - targets_failed
      - targets_waiting
      - done
  DatasetsServiceGetProgressUnauthorizedResponseBody:
    title: DatasetsServiceGetProgressUnauthorizedResponseBody
    type: object
    properties:
      bots_progresses:
        type: object
        description: результат работы по каждому боту, ключ- имя бота
        example:
          Ducimus hic.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
          Et hic dolores earum perferendis nisi.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
          Omnis assumenda molestiae quo quia consequatur.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
        additionalProperties:
          $ref: '#/definitions/BloggersProgressResponseBody'
      done:
        type: boolean
        description: закончена ли задача
        example: false
      targets_failed:
        type: integer
        description: количество аккаунтов, которых не получилось упомянуть, при перезапуске задачи будут использованы заново
        example: 2372612441274165778
        format: int64
      targets_notified:
        type: integer
        description: количество аккаунтов, которых упомянули в постах
        example: 5974723451702194596
        format: int64
      targets_waiting:
        type: integer
        description: количество аккаунтов, которых не выбрали для постов
        example: 486751458840746133
        format: int64
    example:
      bots_progresses:
        Voluptatem ut ipsum.:
          posts_count: 5241754460792455823
          status: 4341670138231604568
          user_name: Magni corrupti earum dolore ab.
      done: true
      targets_failed: 1211602041623664540
      targets_notified: 1586761469937398784
      targets_waiting: 4732767903271408452
    required:
      - bots_progresses
      - targets_notified
      - targets_failed
      - targets_waiting
      - done
  DatasetsServiceParseDatasetBadRequestResponseBody:
    title: DatasetsServiceParseDatasetBadRequestResponseBody
    type: object
    properties:
      dataset_id:
        type: string
        description: id задачи
        example: Sit sit doloremque rerum soluta nulla pariatur.
      status:
        type: integer
        example: 4
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      dataset_id: Animi perspiciatis aut.
      status: 1
    required:
      - dataset_id
      - status
  DatasetsServiceParseDatasetNotFoundResponseBody:
    title: DatasetsServiceParseDatasetNotFoundResponseBody
    type: object
    properties:
      dataset_id:
        type: string
        description: id задачи
        example: Autem ea voluptatum voluptas et eligendi.
      status:
        type: integer
        example: 4
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      dataset_id: Enim architecto.
      status: 3
    required:
      - dataset_id
      - status
  DatasetsServiceParseDatasetOKResponseBody:
    title: DatasetsServiceParseDatasetOKResponseBody
    type: object
    properties:
      dataset_id:
        type: string
        description: id задачи
        example: Ipsam labore.
      status:
        type: integer
        example: 2
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      dataset_id: Vel laborum quisquam ut voluptate expedita ipsa.
      status: 6
    required:
      - dataset_id
      - status
  DatasetsServiceParseDatasetUnauthorizedResponseBody:
    title: DatasetsServiceParseDatasetUnauthorizedResponseBody
    type: object
    properties:
      dataset_id:
        type: string
        description: id задачи
        example: Rem cumque et tempora voluptates.
      status:
        type: integer
        example: 4
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    example:
      dataset_id: Ut deserunt.
      status: 6
    required:
      - dataset_id
      - status
  DatasetsServiceUpdateDatasetNotFoundResponseBody:
    title: DatasetsServiceUpdateDatasetNotFoundResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 1325917588
        format: int32
      id:
        type: string
        example: 2AE5027E-EF4C-E00D-314E-1CB4449A11C0
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 269905666
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 997821163
        format: int32
      status:
        type: integer
        example: 6
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Reprehenderit sed.
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      commented_per_post: 1050414311
      id: 233374F1-297F-8711-5FC3-4F6B3731AD63
      liked_per_post: 1408914937
      posts_per_blogger: 230902202
      status: 4
      title: Aut laborum delectus commodi commodi vel.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
  DatasetsServiceUpdateDatasetOKResponseBody:
    title: DatasetsServiceUpdateDatasetOKResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 2121787775
        format: int32
      id:
        type: string
        example: A129B534-C1FC-F09D-BF29-3DA5781E0ECB
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 198255485
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 1415685313
        format: int32
      status:
        type: integer
        example: 2
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Enim autem temporibus laborum.
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      commented_per_post: 91622038
      id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
      liked_per_post: 427831637
      posts_per_blogger: 674924356
      status: 4
      title: Sunt voluptatem est eos ipsa eos similique.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
  DatasetsServiceUpdateDatasetRequestBody:
    title: DatasetsServiceUpdateDatasetRequestBody
    type: object
    properties:
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 16044480179341848302
        format: int64
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 1507068571979252134
        format: int64
      original_accounts:
        type: array
        items:
          type: string
          example: Quas et aut nihil iste qui.
        description: имена аккаунтов, для которых ищем похожих
        example:
          - Magni beatae.
          - Est aut facere nihil expedita consequatur quia.
      phone_code:
        type: integer
        description: код региона, по которому будем сортировать
        example: 7
        minimum: 1
        maximum: 1000
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 4564337280206112403
        format: int64
      title:
        type: string
        description: название задачи
        example: Sit dolor doloremque provident voluptatem.
    example:
      commented_per_post: 11627789894998437097
      liked_per_post: 15829637107088005580
      original_accounts:
        - Reprehenderit omnis similique ratione.
        - Voluptatem vero molestias.
        - Beatae vitae ea ipsam eligendi sint.
      phone_code: 7
      posts_per_blogger: 3762476979844829310
      title: Sequi aut quis voluptatem expedita in.
  DatasetsServiceUpdateDatasetUnauthorizedResponseBody:
    title: DatasetsServiceUpdateDatasetUnauthorizedResponseBody
    type: object
    properties:
      bloggers:
        type: array
        items:
          $ref: '#/definitions/BloggerResponseBody'
        example:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
      commented_per_post:
        type: integer
        description: сколько прокоментировааших для каждого поста брать
        example: 1588445835
        format: int32
      id:
        type: string
        example: A8E7C55C-B3EA-B228-EF84-9DB3D55D57A4
        format: uuid
      liked_per_post:
        type: integer
        description: сколько лайкнувших для каждого поста брать
        example: 2109870417
        format: int32
      posts_per_blogger:
        type: integer
        description: имена аккаунтов, для которых ищем похожих
        example: 1595072188
        format: int32
      status:
        type: integer
        example: 1
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      title:
        type: string
        description: название задачи
        example: Alias ipsa sunt.
    example:
      bloggers:
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
        - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
          id: 74C53540-E974-ABFF-2565-6BF99F9017B2
          is_initial: false
          user_id: 6195190025290612606
          username: Optio mollitia nam.
      commented_per_post: 454529169
      id: 1576BB1F-D21C-05AD-6677-73725A387FA6
      liked_per_post: 79656612
      posts_per_blogger: 169917170
      status: 1
      title: Animi ipsa qui a consequatur.
    required:
      - id
      - bloggers
      - status
      - title
      - posts_per_blogger
      - liked_per_post
      - commented_per_post
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".

      **Security Scopes**:
        * `driver`: Read-only access
        * `admin`: Read and write access
    name: Authorization
    in: header
