openapi: 3.0.3
info:
  title: REST api for simple route app
  version: "1.0"
servers:
  - url: /
    description: Default server for rest-api
paths:
  /api/datasets/:
    get:
      tags:
        - datasets_service
      summary: list datasets datasets_service
      description: получить все задачи для текущего пользователя
      operationId: datasets_service#list datasets
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
                example:
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
              example:
                - bloggers:
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                  commented_per_post: 1433924079
                  id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                  liked_per_post: 606835097
                  posts_per_blogger: 1998950640
                  status: 5
                  title: Omnis reiciendis illo maiores dolorem quia.
                - bloggers:
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                  commented_per_post: 1433924079
                  id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                  liked_per_post: 606835097
                  posts_per_blogger: 1998950640
                  status: 5
                  title: Omnis reiciendis illo maiores dolorem quia.
                - bloggers:
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                    - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                      is_initial: false
                      user_id: 7194315760384879922
                      username: Alias blanditiis provident voluptatem.
                  commented_per_post: 1433924079
                  id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                  liked_per_post: 606835097
                  posts_per_blogger: 1998950640
                  status: 5
                  title: Omnis reiciendis illo maiores dolorem quia.
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                type: string
                example: Sapiente vitae aliquam.
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
                example:
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
                example:
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
                example:
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
                  - bloggers:
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                      - dataset_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
                        id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
                        is_initial: false
                        user_id: 7194315760384879922
                        username: Alias blanditiis provident voluptatem.
                    commented_per_post: 1433924079
                    id: 5E3B665E-1239-9C12-9643-FFC1E6C04697
                    liked_per_post: 606835097
                    posts_per_blogger: 1998950640
                    status: 5
                    title: Omnis reiciendis illo maiores dolorem quia.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
  /api/datasets/{dataset_id}/:
    get:
      tags:
        - datasets_service
      summary: get dataset datasets_service
      description: получить задачу по id
      operationId: datasets_service#get dataset
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          schema:
            type: string
            description: id задачи
            example: Tempora et possimus voluptatem assumenda nisi rerum.
          example: Animi et omnis.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
              example:
                bloggers:
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                commented_per_post: 643031576
                id: 773F4E7F-A748-DF6D-4355-233071D2534A
                liked_per_post: 1615893931
                posts_per_blogger: 958023306
                status: 2
                title: Quia et laudantium cum.
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                type: string
                example: Minus alias error adipisci est aliquam qui.
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: string
                example: Aut perspiciatis odio illo ducimus sed.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
    put:
      tags:
        - datasets_service
      summary: update dataset datasets_service
      description: |-
        обновить информацию о задаче. Не меняет статус задачи, можно вызывать сколько угодно раз.
        			Нельзя вызвать для задачи, которая уже выполняется, для этого надо сначала остановить выполнение.
      operationId: datasets_service#update dataset
      parameters:
        - name: dataset_id
          in: path
          description: id задачи, которую хотим обновить
          required: true
          schema:
            type: string
            description: id задачи, которую хотим обновить
            example: Unde dicta.
          example: Cum voluptas voluptates iure alias et.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDatasetRequestBody'
            example:
              commented_per_post: 14756509802797021993
              liked_per_post: 12621172150073358936
              original_accounts:
                - Qui rerum molestiae adipisci voluptatem.
                - Odio qui molestiae consequatur quia doloremque fugit.
                - Sed culpa.
                - Deleniti dolorem molestiae eos exercitationem consequatur eligendi.
              phone_code: 7
              posts_per_blogger: 7917445315319735926
              title: Perferendis eius.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
              example:
                bloggers:
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                commented_per_post: 493751028
                id: 2C91774A-6D4A-67B6-DC43-6AED849DACC1
                liked_per_post: 2062261290
                posts_per_blogger: 1316725725
                status: 6
                title: Magni aut.
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                type: string
                example: Nesciunt totam in laudantium id.
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: string
                example: Sapiente est.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
  /api/datasets/{dataset_id}/progress/:
    get:
      tags:
        - datasets_service
      summary: get progress datasets_service
      description: получить статус выполнения задачи по id
      operationId: datasets_service#get progress
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          schema:
            type: string
            description: id задачи
            example: Et itaque pariatur et illum itaque officia.
          example: Eum cupiditate.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetProgress'
              example:
                bots_progresses:
                  Corporis a reiciendis adipisci vitae.:
                    posts_count: 5241754460792455823
                    status: 4341670138231604568
                    user_name: Magni corrupti earum dolore ab.
                done: false
                targets_failed: 7543780231117535126
                targets_notified: 797476817121968289
                targets_waiting: 8110972934114118665
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                type: string
                example: Aut officia nemo nisi.
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetProgress'
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetProgress'
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: string
                example: Tempore ut consequatur.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
  /api/datasets/{dataset_id}/start/:
    post:
      tags:
        - datasets_service
      summary: find similar datasets_service
      description: 'начать выполнение задачи '
      operationId: datasets_service#find similar
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          schema:
            type: string
            description: id задачи
            example: Sunt magnam incidunt voluptatibus.
          example: Non quidem saepe aut saepe.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindSimilarOKResponseBody'
              example:
                bloggers:
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                  - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
                    id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                    is_initial: false
                    user_id: 6195190025290612606
                    username: Optio mollitia nam.
                dataset_id: Corporis fugit fugiat ex quisquam itaque nisi.
                status: 2
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindSimilarOKResponseBody'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindSimilarOKResponseBody'
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindSimilarOKResponseBody'
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: string
                example: Sunt rerum saepe.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
  /api/datasets/{dataset_id}/stop/:
    post:
      tags:
        - datasets_service
      summary: parse dataset datasets_service
      description: получить базу доноров для выбранных блогеров
      operationId: datasets_service#parse dataset
      parameters:
        - name: dataset_id
          in: path
          description: id задачи
          required: true
          schema:
            type: string
            description: id задачи
            example: Praesentium enim maiores officia non dolore quia.
          example: Maiores architecto ipsam labore officiis quia et.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParseDatasetOKResponseBody'
              example:
                dataset_id: Maiores accusantium illum rem molestiae qui fugiat.
                status: 2
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParseDatasetOKResponseBody'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParseDatasetOKResponseBody'
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParseDatasetOKResponseBody'
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: string
                example: In veniam dolore facilis necessitatibus.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
  /api/datasets/draft/:
    post:
      tags:
        - datasets_service
      summary: create dataset draft datasets_service
      description: создать драфт задачи
      operationId: datasets_service#create dataset draft
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                description: dataset_id для созданной задачи
                example: 35814117-F834-9FAB-0A03-DB6E91CE1F7F
                format: uuid
              example: EBC096AD-D9EC-2F9C-CCD5-2819684939D3
        "400":
          description: 'bad request: Bad Request response.'
          content:
            application/json:
              schema:
                type: string
                example: Dolor odit aliquam ut.
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                type: string
                description: dataset_id для созданной задачи
                example: 5D93A99A-535C-03BB-87BD-865144549E25
                format: uuid
        "404":
          description: 'dataset not found: Not Found response.'
          content:
            application/json:
              schema:
                type: string
                description: dataset_id для созданной задачи
                example: E6770800-709B-577A-95B9-5007000379C3
                format: uuid
        "500":
          description: 'internal error: Internal Server Error response.'
          content:
            application/json:
              schema:
                type: string
                example: Iure atque adipisci tempora enim voluptatem.
      security:
        - jwt_header_Authorization:
            - driver
            - admin
components:
  schemas:
    Blogger:
      type: object
      properties:
        dataset_id:
          type: string
          description: айди датасета, к которому принадлежит блоггер
          example: 8B791A71-1C43-AB9B-4366-12192353E1A2
          format: uuid
        id:
          type: string
          example: 6E989AEF-9C11-4862-D8B1-5CFC4F6414E0
          format: uuid
        is_initial:
          type: boolean
          description: является ли блоггер изначально в датасете или появился при парсинге
          example: true
        user_id:
          type: integer
          description: user_id в инстаграме, -1 если неизвестен
          example: 725361841190412921
          format: int64
        username:
          type: string
          description: имя аккаунта в инстаграме
          example: Eaque similique dignissimos nesciunt laudantium ut dolor.
      example:
        dataset_id: 799C598D-49D1-F53A-0ED6-818482028C45
        id: A1E767AB-DA97-F23F-D106-18BF8653EB6C
        is_initial: true
        user_id: 1320813824970598171
        username: Vel odio quia aliquid.
      required:
        - id
        - dataset_id
        - username
        - is_initial
        - user_id
    BloggersProgress:
      type: object
      properties:
        posts_count:
          type: integer
          description: количество выложенных постов
          example: 1255921548311326738
          format: int64
        status:
          type: integer
          description: текущий статус бота, будут ли выкладываться посты
          example: 6509098127544037273
          format: int64
        user_name:
          type: string
          description: имя пользователя бота
          example: Vel laborum natus dolores voluptatem necessitatibus sed.
      example:
        posts_count: 1618258270713292886
        status: 7128797357094996647
        user_name: Ut eveniet sed sunt aliquam quibusdam qui.
      required:
        - user_name
        - posts_count
        - status
    Dataset:
      type: object
      properties:
        bloggers:
          type: array
          items:
            $ref: '#/components/schemas/Blogger'
          example:
            - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
              id: 74C53540-E974-ABFF-2565-6BF99F9017B2
              is_initial: false
              user_id: 6195190025290612606
              username: Optio mollitia nam.
            - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
              id: 74C53540-E974-ABFF-2565-6BF99F9017B2
              is_initial: false
              user_id: 6195190025290612606
              username: Optio mollitia nam.
        commented_per_post:
          type: integer
          description: сколько прокоментировааших для каждого поста брать
          example: 918285950
          format: int32
        id:
          type: string
          example: 6BD40BD6-7AF6-FB4E-C1C1-23700A0E68DE
          format: uuid
        liked_per_post:
          type: integer
          description: сколько лайкнувших для каждого поста брать
          example: 116643595
          format: int32
        posts_per_blogger:
          type: integer
          description: имена аккаунтов, для которых ищем похожих
          example: 633153139
          format: int32
        status:
          type: integer
          example: 6
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
        title:
          type: string
          description: название задачи
          example: Occaecati possimus iure dicta.
      example:
        bloggers:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
        commented_per_post: 861541666
        id: D16B2ED1-3971-5178-0135-F3E819F3BA4F
        liked_per_post: 1890767501
        posts_per_blogger: 207989125
        status: 2
        title: Qui quia animi et saepe distinctio quaerat.
      required:
        - id
        - bloggers
        - status
        - title
        - posts_per_blogger
        - liked_per_post
        - commented_per_post
    DatasetProgress:
      type: object
      properties:
        bots_progresses:
          type: object
          description: результат работы по каждому боту, ключ- имя бота
          example:
            Nihil ut enim eveniet.:
              posts_count: 5241754460792455823
              status: 4341670138231604568
              user_name: Magni corrupti earum dolore ab.
          additionalProperties:
            $ref: '#/components/schemas/BloggersProgress'
        done:
          type: boolean
          description: закончена ли задача
          example: true
        targets_failed:
          type: integer
          description: количество аккаунтов, которых не получилось упомянуть, при перезапуске задачи будут использованы заново
          example: 1521977625192955082
          format: int64
        targets_notified:
          type: integer
          description: количество аккаунтов, которых упомянули в постах
          example: 2349749605387729941
          format: int64
        targets_waiting:
          type: integer
          description: количество аккаунтов, которых не выбрали для постов
          example: 6304856710523120734
          format: int64
      example:
        bots_progresses:
          Officia adipisci.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
          Tempore laboriosam unde cupiditate est voluptatum.:
            posts_count: 5241754460792455823
            status: 4341670138231604568
            user_name: Magni corrupti earum dolore ab.
        done: false
        targets_failed: 1752804748307497791
        targets_notified: 6364492188904649740
        targets_waiting: 179264826678926416
      required:
        - bots_progresses
        - targets_notified
        - targets_failed
        - targets_waiting
        - done
    FindSimilarOKResponseBody:
      type: object
      properties:
        bloggers:
          type: array
          items:
            $ref: '#/components/schemas/Blogger'
          example:
            - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
              id: 74C53540-E974-ABFF-2565-6BF99F9017B2
              is_initial: false
              user_id: 6195190025290612606
              username: Optio mollitia nam.
            - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
              id: 74C53540-E974-ABFF-2565-6BF99F9017B2
              is_initial: false
              user_id: 6195190025290612606
              username: Optio mollitia nam.
        dataset_id:
          type: string
          description: id задачи
          example: Possimus illum omnis quam dolorum soluta.
        status:
          type: integer
          example: 6
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
      example:
        bloggers:
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
          - dataset_id: FB1E8AC6-4FA4-C883-ED5A-54960E88F5FE
            id: 74C53540-E974-ABFF-2565-6BF99F9017B2
            is_initial: false
            user_id: 6195190025290612606
            username: Optio mollitia nam.
        dataset_id: Omnis sit quia beatae quasi voluptatem.
        status: 1
      required:
        - dataset_id
        - status
        - bloggers
    ParseDatasetOKResponseBody:
      type: object
      properties:
        dataset_id:
          type: string
          description: id задачи
          example: Sunt sit aut sequi aut harum.
        status:
          type: integer
          example: 2
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
      example:
        dataset_id: Est architecto deleniti quis quam ducimus.
        status: 6
      required:
        - dataset_id
        - status
    UpdateDatasetRequestBody:
      type: object
      properties:
        commented_per_post:
          type: integer
          description: сколько прокоментировааших для каждого поста брать
          example: 11101775644301025150
        liked_per_post:
          type: integer
          description: сколько лайкнувших для каждого поста брать
          example: 17149570722218992909
        original_accounts:
          type: array
          items:
            type: string
            example: Excepturi pariatur.
          description: имена аккаунтов, для которых ищем похожих
          example:
            - Qui ut.
            - Vel id.
            - Explicabo voluptate velit sunt accusamus velit similique.
            - Aut rem nisi omnis ad quia.
        phone_code:
          type: integer
          description: код региона, по которому будем сортировать
          example: 7
          minimum: 1
          maximum: 1000
        posts_per_blogger:
          type: integer
          description: имена аккаунтов, для которых ищем похожих
          example: 8912691761507832878
        title:
          type: string
          description: название задачи
          example: Voluptate eius doloribus et quae.
      example:
        commented_per_post: 6434592887515454813
        liked_per_post: 7709647894738480529
        original_accounts:
          - Porro doloremque explicabo aut maiores aperiam.
          - Aliquam illo iste.
        phone_code: 7
        posts_per_blogger: 4187497416852408894
        title: Sunt est est sit.
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".
      scheme: bearer
tags:
  - name: datasets_service
    description: сервис для создания, редактирования и работы с задачами (рекламными компаниями)
